// <auto-generated />
using System;
using DepEdLogbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepEdLogbook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505004528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepEdLogbook.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Unit = "ADMIN",
                            UnitFullName = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Accounting2026",
                            Role = "Staff",
                            Unit = "ACCOUNTING",
                            UnitFullName = "Accounting Unit",
                            Username = "AccountingUnit"
                        },
                        new
                        {
                            Id = 3,
                            Password = "sdo123",
                            Role = "Staff",
                            Unit = "SDO",
                            UnitFullName = "Schools Division Office",
                            Username = "sdo"
                        },
                        new
                        {
                            Id = 4,
                            Password = "asds123",
                            Role = "Staff",
                            Unit = "ASDS",
                            UnitFullName = "Assistant Schools Division Superintendent",
                            Username = "asds"
                        },
                        new
                        {
                            Id = 5,
                            Password = "records123",
                            Role = "Staff",
                            Unit = "RECORDS",
                            UnitFullName = "Records Section",
                            Username = "records"
                        },
                        new
                        {
                            Id = 6,
                            Password = "hr123",
                            Role = "Staff",
                            Unit = "HR",
                            UnitFullName = "Human Resource Section",
                            Username = "hr"
                        },
                        new
                        {
                            Id = 7,
                            Password = "lr123",
                            Role = "Staff",
                            Unit = "LR",
                            UnitFullName = "Learning Resources Section",
                            Username = "lr"
                        },
                        new
                        {
                            Id = 8,
                            Password = "sgod123",
                            Role = "Staff",
                            Unit = "SGOD",
                            UnitFullName = "School Governance and Operations Division",
                            Username = "sgod"
                        },
                        new
                        {
                            Id = 9,
                            Password = "cid123",
                            Role = "Staff",
                            Unit = "CID",
                            UnitFullName = "Curriculum and Instruction Division",
                            Username = "cid"
                        },
                        new
                        {
                            Id = 10,
                            Password = "budget123",
                            Role = "Staff",
                            Unit = "BUDGET",
                            UnitFullName = "Budget Section",
                            Username = "budget"
                        },
                        new
                        {
                            Id = 11,
                            Password = "bac123",
                            Role = "Staff",
                            Unit = "BAC",
                            UnitFullName = "Bids and Awards Committee",
                            Username = "bac"
                        },
                        new
                        {
                            Id = 12,
                            Password = "cash123",
                            Role = "Staff",
                            Unit = "CASH",
                            UnitFullName = "Cash Section",
                            Username = "cash"
                        },
                        new
                        {
                            Id = 13,
                            Password = "admin_unit123",
                            Role = "Staff",
                            Unit = "ADMIN_UNIT",
                            UnitFullName = "Administrative Division",
                            Username = "admin_unit"
                        },
                        new
                        {
                            Id = 14,
                            Password = "sds123",
                            Role = "Staff",
                            Unit = "SDS",
                            UnitFullName = "Schools Division Superintendent",
                            Username = "sds"
                        },
                        new
                        {
                            Id = 15,
                            Password = "supply123",
                            Role = "Staff",
                            Unit = "SUPPLY",
                            UnitFullName = "Supply and Property Unit",
                            Username = "supply"
                        },
                        new
                        {
                            Id = 16,
                            Password = "legal123",
                            Role = "Staff",
                            Unit = "LEGAL",
                            UnitFullName = "Legal Unit",
                            Username = "legal"
                        });
                });

            modelBuilder.Entity("DepEdLogbook.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DepEdLogbook.Models.DocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogbookEntryId")
                        .HasColumnType("int");

                    b.Property<string>("Particulars")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogbookEntryId");

                    b.ToTable("DocumentItems");
                });

            modelBuilder.Entity("DepEdLogbook.Models.LogbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogbookEntries");
                });

            modelBuilder.Entity("DepEdLogbook.Models.DocumentItem", b =>
                {
                    b.HasOne("DepEdLogbook.Models.LogbookEntry", "LogbookEntry")
                        .WithMany("Documents")
                        .HasForeignKey("LogbookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogbookEntry");
                });

            modelBuilder.Entity("DepEdLogbook.Models.LogbookEntry", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
